import 'package:flutter/material.dart';

/// Represents the role of a chat participant.
enum MessageRole {
  /// Message sent by the human user.
  user,

  /// Message generated by the AI assistant.
  assistant,

  /// System-level message (e.g. context injections, tool results).
  system,
}

/// Represents the type of content in a message.
enum MessageContentType {
  /// Plain text or Markdown content.
  text,

  /// Currently streaming — content may be partial.
  streaming,

  /// Message is a loading/thinking placeholder.
  loading,
}

/// A single chat message in the AI conversation.
///
/// ```dart
/// final msg = ChatMessage.user(
///   text: 'Hello, how are you?',
///   avatarUrl: 'https://example.com/user.png',
/// );
/// ```
class ChatMessage {
  /// Unique identifier for this message.
  final String id;

  /// The role of the message sender.
  final MessageRole role;

  /// The text content of the message (supports Markdown).
  final String text;

  /// When the message was created.
  final DateTime timestamp;

  /// Optional URL or asset path for the sender's avatar.
  final String? avatarUrl;

  /// Optional widget to use as avatar instead of a URL.
  final Widget? avatarWidget;

  /// Display name of the sender.
  final String? senderName;

  /// Content type — affects rendering behavior.
  final MessageContentType contentType;

  /// Reactions added to this message.
  final List<String> reactions;

  /// Whether the message has been read.
  final bool isRead;

  /// Optional metadata (e.g. model name, token count).
  final Map<String, dynamic>? metadata;

  const ChatMessage({
    required this.id,
    required this.role,
    required this.text,
    required this.timestamp,
    this.avatarUrl,
    this.avatarWidget,
    this.senderName,
    this.contentType = MessageContentType.text,
    this.reactions = const [],
    this.isRead = false,
    this.metadata,
  });

  /// Creates a user message.
  factory ChatMessage.user({
    required String text,
    String? id,
    String? avatarUrl,
    Widget? avatarWidget,
    String? senderName,
    Map<String, dynamic>? metadata,
  }) {
    return ChatMessage(
      id: id ?? _generateId(),
      role: MessageRole.user,
      text: text,
      timestamp: DateTime.now(),
      avatarUrl: avatarUrl,
      avatarWidget: avatarWidget,
      senderName: senderName ?? 'You',
      metadata: metadata,
    );
  }

  /// Creates an assistant message.
  factory ChatMessage.assistant({
    required String text,
    String? id,
    String? avatarUrl,
    Widget? avatarWidget,
    String? senderName,
    MessageContentType contentType = MessageContentType.text,
    Map<String, dynamic>? metadata,
  }) {
    return ChatMessage(
      id: id ?? _generateId(),
      role: MessageRole.assistant,
      text: text,
      timestamp: DateTime.now(),
      avatarUrl: avatarUrl,
      avatarWidget: avatarWidget,
      senderName: senderName ?? 'AI Assistant',
      contentType: contentType,
      metadata: metadata,
    );
  }

  /// Creates a loading placeholder message.
  factory ChatMessage.loading({String? id}) {
    return ChatMessage(
      id: id ?? _generateId(),
      role: MessageRole.assistant,
      text: '',
      timestamp: DateTime.now(),
      contentType: MessageContentType.loading,
      senderName: 'AI Assistant',
    );
  }

  /// Returns true if this message is from the user.
  bool get isUser => role == MessageRole.user;

  /// Returns true if this message is from the assistant.
  bool get isAssistant => role == MessageRole.assistant;

  /// Returns true if this is a streaming message.
  bool get isStreaming => contentType == MessageContentType.streaming;

  /// Returns true if this is a loading indicator.
  bool get isLoading => contentType == MessageContentType.loading;

  /// Creates a copy of this message with updated fields.
  ChatMessage copyWith({
    String? id,
    MessageRole? role,
    String? text,
    DateTime? timestamp,
    String? avatarUrl,
    Widget? avatarWidget,
    String? senderName,
    MessageContentType? contentType,
    List<String>? reactions,
    bool? isRead,
    Map<String, dynamic>? metadata,
  }) {
    return ChatMessage(
      id: id ?? this.id,
      role: role ?? this.role,
      text: text ?? this.text,
      timestamp: timestamp ?? this.timestamp,
      avatarUrl: avatarUrl ?? this.avatarUrl,
      avatarWidget: avatarWidget ?? this.avatarWidget,
      senderName: senderName ?? this.senderName,
      contentType: contentType ?? this.contentType,
      reactions: reactions ?? this.reactions,
      isRead: isRead ?? this.isRead,
      metadata: metadata ?? this.metadata,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage && runtimeType == other.runtimeType && id == other.id;

  @override
  int get hashCode => id.hashCode;

  static String _generateId() => 'msg_${DateTime.now().microsecondsSinceEpoch}';
}
